### ISSUE TITLE
Alfred 4: syntax error.

### ISSUE THREAD

**Issue by politicus** [vdesabou/alfred-mac-osx-sharing#2]
Got this error message as I was trying to share a file using a file action:

> [11:28:00.206] Logging Stopped.
> [17:05:40.940] Logging Started...
> [17:07:43.170] Logging Stopped.
> [06:37:47.701] Logging Started...
> [06:37:55.365] Productivity Mac OS X Sharing[File Action] Processing complete
> [06:37:55.424] Productivity Mac OS X Sharing[File Action] Passing output '/Volumes/Test/Test/Test/test.zip' to Run Script
> [06:37:55.972] ERROR: Productivity Mac OS X Sharing[Run Script] 31:39: syntax error: A “"” can’t go after this identifier. (-2740)

**Comment by vdesabou** [comment]
I don't really use this workflow myself, but I guess you just need to update :

<img width="732" alt="Screenshot 2019-09-02 at 13 22 30" src="https://user-images.githubusercontent.com/4061923/64111391-df76e900-cd84-11e9-9475-d6c597ddd088.png">


with "Alfred 4" instead of "Alfred 3"

<img width="778" alt="Screenshot 2019-09-02 at 13 23 06" src="https://user-images.githubusercontent.com/4061923/64111434-f6b5d680-cd84-11e9-8494-29cd7c3392f4.png">

**Comment by politicus** [comment]
I guess you just made my day. Thank you!
